# Adapted from Dockerfile
name: Build Wget-AT binary
run-name: Build ${{ github.ref }}
on: [push]
jobs:
  build-binary:
    runs-on: ubuntu-22.04
    container:
      # Buster is supported by LTS until 2024-06-30
      image: debian:buster-slim
      # https://github.com/ImageMagick/ImageMagick/blob/eaa6f6c1670972fac0a43a9b624ef58099092a41/.github/workflows/app-image.yml#L24
      options: --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined
      env:
        TLSTYPE: openssl
        LC_ALL: C
    steps:
      - name: Install build dependencies
        run: |
          set -eux
          case "${TLSTYPE}" in
            openssl) SSLPKG=libssl-dev;;
            gnutls) SSLPKG=gnutls-dev;;
            *) echo "Unknown TLSTYPE ${TLSTYPE}"; exit 1;;
          esac
          DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get -qqy --no-install-recommends -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-unsafe-io update
          DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get -qqy --no-install-recommends -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-unsafe-io upgrade
          DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical apt-get -qqy --no-install-recommends -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-unsafe-io install "${SSLPKG}" build-essential git bzip2 bash rsync gcc zlib1g-dev autoconf autoconf-archive flex make automake gettext libidn11 autopoint texinfo gperf ca-certificates wget pkg-config libpsl-dev libidn2-dev libluajit-5.1-dev libgpgme-dev libpcre2-dev git

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install zstd
        run: |
          cd /tmp
          wget https://github.com/facebook/zstd/releases/download/v1.4.4/zstd-1.4.4.tar.gz
          tar xf zstd-1.4.4.tar.gz
          cd zstd-1.4.4
          make
          make install

      - name: Install c-ares
        run: |
          cd /tmp
          wget https://github.com/c-ares/c-ares/releases/download/cares-1_19_1/c-ares-1.19.1.tar.gz
          tar xf c-ares-1.19.1.tar.gz
          cd c-ares-1.19.1
          ./configure
          make
          make install

      - name: Update ld cache
        run: ldconfig

      - name: Compile
        run: |
          ls -l .git
          id
          git config --global --add safe.directory '*'
          ./bootstrap
          ./configure --with-ssl="${TLSTYPE}" --with-cares --disable-nls
          make -j $(nproc)
          src/wget --help | grep -iE "gnu|warc|lua|dns|host|resolv"

      - name: Build AppImage
        run: |
          set -e
          mkdir -p .github/workflows/AppImage/appdir/usr/bin/
          cp src/wget .github/workflows/AppImage/appdir/usr/bin/
          cd .github/workflows/AppImage
          wget https://github.com/linuxdeploy/linuxdeploy/releases/latest/download/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          ./linuxdeploy-x86_64.AppImage --appimage-extract
          ./squashfs-root/AppRun --appdir appdir --output appimage

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            .github/workflows/AppImage/wget-AT-*.AppImage
